name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3 python3-dev python3-pip
        sudo apt install -y openjdk-11-jdk
        sudo apt install -y libffi-dev libssl-dev zlib1g-dev
        sudo apt install -y autoconf automake libtool pkg-config
        sudo apt install -y cmake
        pip3 install --upgrade pip setuptools
        pip3 install cython
        pip3 install kivy buildozer python-for-android opencv-python numpy

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: polar-align-apk
        path: bin/*.apk
